title: Ashwini Marathe # your name (or website title) here
logo: "/images/51264.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  MS Interdisciplinary Data Science'21 at Duke University
  <br><br>
  Finding patterns in data excites me and hence I have embarked on this Data Scince journey. 
  <br><br>
  <a href="https://www.linkedin.com/in/ashwini-marathe/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
